name: type check and test

on: pull_request

jobs:
  type-check-and-build-test:
    name: type check and test
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno lint .
      - run: deno test .
      - run: deno publish --dry-run
